# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('corporation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manual', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='assessment_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Program'),
        ),
    ]
