# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devices_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='imageURL',
            field=models.TextField(default=''),
        ),
    ]
